script: |
  # -------------------------
  # Login to ECR
  # -------------------------
  aws ecr get-login-password --region us-east-2 \
  | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-2.amazonaws.com

  # -------------------------
  # Pull latest image
  # -------------------------
  docker pull ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-2.amazonaws.com/devops-api:latest

  # -------------------------
  # Clean old container
  # -------------------------
  docker stop aws-devops-app || true
  docker rm aws-devops-app || true

  # -------------------------
  # Run Docker ONLY on 3000
  # -------------------------
  docker run -d \
    --name aws-devops-app \
    --network devops-network \
    -p 3000:3000 \
    -e MONGO_URI="${{ secrets.MONGO_URI }}" \
    ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-2.amazonaws.com/devops-api:latest

  # -------------------------
  # Ensure nginx installed
  # -------------------------
  sudo dnf install nginx -y || true

  # -------------------------
  # Create nginx reverse proxy config
  # -------------------------
  sudo tee /etc/nginx/conf.d/devops.conf > /dev/null <<EOF
server {
    listen 80;
    server_name adrian-devops.site www.adrian-devops.site;

    location / {
        proxy_pass http://127.0.0.1:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
EOF

  # -------------------------
  # Restart nginx
  # -------------------------
  sudo systemctl enable nginx
  sudo systemctl restart nginx
